#ifndef TPV_INTERNAL_H
#define TPV_INTERNAL_H
#include <stdint.h>
#include <assert.h>
#include "tpv_config.h"
#include "tpv.h"

/* spec §6: field order locked for AAPCS to be exactly 80 B */
typedef struct {
    int64_t mu20, mu11, mu02;
    int64_t mu30, mu21, mu12, mu03;
    int32_t m00, m10, m01;
    int32_t perimeter;
    int16_t bbox_x0, bbox_y0, bbox_x1, bbox_y1;
} tpv_Blob;
_Static_assert(sizeof(tpv_Blob) == 80, "Blob layout drift — fix field order");

typedef struct {
    int32_t hu[7];
    int32_t perim_ratio;
    int32_t eccentricity;
    int32_t m3_axis_sign;
} tpv_Features;
_Static_assert(sizeof(tpv_Features) == 40, "Features layout drift");

typedef struct {
    tpv_Features mean;
    int32_t L_inv[TPV_L_INV_N];
    int32_t reject_thresh;
    int32_t margin;
} tpv_Template;

/* spec §4.2 module contracts */
void tpv_threshold(const uint8_t *y, int w, int h, uint8_t *bin_out);
int  tpv_ccl_moments(const uint8_t *bin, int w, int h,
                     tpv_Blob *blobs_out, int max_blobs);
void tpv_shape_features(const tpv_Blob *blob, tpv_Features *features_out);
void tpv_classify(const tpv_Features *f,
                  const tpv_Template *tmpl, int n_templates,
                  uint8_t *class_id_out,
                  uint8_t *confidence_out,
                  int32_t *d1_sq_out);
void tpv_pose(const tpv_Blob *blob,
              int16_t *x_out, int16_t *y_out, int16_t *theta_x10_out);

/* Generated by calibration tool, must exist at link time on target */
extern const tpv_Template tpv_templates[TPV_N_CLASSES];
extern const uint8_t      tpv_bin_threshold;

/* Fixed-point math helpers (in src/fixed_math.c), used by multiple modules */
int64_t tpv_isqrt_q16(int64_t x_q16);
int32_t tpv_log_q16(int64_t x_q16);
int32_t tpv_atan2_q16(int64_t y, int64_t x);

#endif
