#ifndef TPV_INTERNAL_H
#define TPV_INTERNAL_H
#include <stdint.h>
#include <assert.h>
#include "tpv_config.h"
#include "tpv.h"

/* spec §6: field order locked for AAPCS to be exactly 80 B */
typedef struct {
    int64_t mu20, mu11, mu02;
    int64_t mu30, mu21, mu12, mu03;
    int32_t m00, m10, m01;
    int32_t perimeter;
    int16_t bbox_x0, bbox_y0, bbox_x1, bbox_y1;
} tpv_Blob;
_Static_assert(sizeof(tpv_Blob) == 80, "Blob layout drift — fix field order");

typedef struct {
    int32_t hu[7];
    int32_t perim_ratio;
    int32_t eccentricity;
    int32_t m3_axis_sign;
} tpv_Features;
_Static_assert(sizeof(tpv_Features) == 40, "Features layout drift");

typedef struct {
    tpv_Features mean;
    int32_t L_inv[TPV_L_INV_N];
    int32_t reject_thresh;
    int32_t margin;
} tpv_Template;

/* spec §4.2 module contracts */
void tpv_threshold(const uint8_t *y, int w, int h, uint8_t *bin_out);
int  tpv_ccl_moments(const uint8_t *bin, int w, int h,
                     tpv_Blob *blobs_out, int max_blobs,
                     uint16_t *labels_out);
void tpv_shape_features(const tpv_Blob *blob, tpv_Features *features_out);
void tpv_classify(const tpv_Features *f,
                  const tpv_Template *tmpl, int n_templates,
                  uint8_t *class_id_out,
                  uint8_t *confidence_out,
                  int32_t *d1_sq_out);
void tpv_pose(const tpv_Blob *blob,
              int16_t *x_out, int16_t *y_out, int16_t *theta_x10_out);

/* Generated by calibration tool, must exist at link time on target.
 * tpv_bin_threshold's qualifier is conditional: the calibration build must
 * be able to write to it (Otsu estimate replaces the default before sample
 * feature extraction). Runtime sees it as const. */
extern const tpv_Template tpv_templates[TPV_N_CLASSES];
#ifdef TPV_CAL_BUILD
extern uint8_t            tpv_bin_threshold;
#else
extern const uint8_t      tpv_bin_threshold;
#endif

/* Fixed-point math helpers (in src/fixed_math.c), used by multiple modules */
int64_t tpv_isqrt_q16(int64_t x_q16);
int64_t tpv_isqrt_i64(int64_t x);                /* plain floor(sqrt) for large int64 */
int32_t tpv_log_q16(int64_t x_q16);
int32_t tpv_atan2_q16(int64_t y, int64_t x);

#ifdef TPV_DEBUG_FEATURES
typedef struct {
    tpv_Detection det;
    tpv_Features  features;
    int32_t       distances_sq[TPV_N_CLASSES];
} tpv_DetectionDebug;

/* Per-template squared Mahalanobis distance, exposed only under
 * TPV_DEBUG_FEATURES so tpv_process_frame_debug can fill the
 * distances_sq[] array. Thin wrapper around the file-static
 * mahal_sq_q16 inside classifier.c. */
int64_t tpv_mahal_sq_q16(const tpv_Features *f, const tpv_Template *tmpl);

int tpv_process_frame_debug(const uint8_t *y, int w, int h,
                            tpv_DetectionDebug *out);

/* v2 debug entry point (spec §4). Runtime-tunable threshold +
 * dark-object-mode + ROI rect; emits three 38400 B bitmaps (bin after
 * threshold+ROI, all CCL blobs, winning blob) plus winner bbox / area /
 * 8x8 grid. Non-OK returns zero the entire struct (spec §4.4). */
typedef struct {
    tpv_Detection det;
    tpv_Features  features;
    int32_t       distances_sq[TPV_N_CLASSES];

    /* bbox_x1, bbox_y1 are INCLUSIVE endpoints — same convention as tpv_Blob
     * (verified in src/ccl_moments.c: bbox is grown via `x > bbox_x1` on
     * actual pixel coords at ~line 111, and Pass 3 iterates `x <= bbox_x1`
     * at ~line 149, i.e. a closed interval).
     * JNI layer in tpv_jni.c must convert to (x, y, w, h) for Kotlin TpvBbox:
     *    x = bbox_x0
     *    y = bbox_y0
     *    w = bbox_x1 - bbox_x0 + 1
     *    h = bbox_y1 - bbox_y0 + 1 */
    int16_t  bbox_x0, bbox_y0, bbox_x1, bbox_y1;
    int32_t  area_px;
    int32_t  grid_8x8;
    uint8_t  bin[TPV_WIDTH * TPV_HEIGHT / 8];
    uint8_t  all_blobs_mask[TPV_WIDTH * TPV_HEIGHT / 8];
    uint8_t  mask[TPV_WIDTH * TPV_HEIGHT / 8];
} tpv_DetectionDebugV2;

int tpv_process_frame_debug_v2(
    const uint8_t *y, int w, int h,
    uint8_t bin_threshold,
    int dark_object_mode,
    int roi_x, int roi_y, int roi_w, int roi_h,
    tpv_DetectionDebugV2 *out);

struct tpv_vision_context;
int tpv_vision_last_debug_v2(const struct tpv_vision_context *ctx,
                             tpv_DetectionDebugV2 *out);
#endif  /* TPV_DEBUG_FEATURES */

#endif
